version: '3.8'
services:
  # frontend:
  #   container_name: 'frontend'
  #   build:
  #     dockerfile: Dockerfile
  #     context: './frontend'
  #   environment:
  #     - NODE_ENV=production
  #   volumes:
  #     - .:/usr/src/app
  #   depends_on:
  #     - node
  #   ports:
  #     - '80:80'
  #   networks:
  #     - default
  #   restart: always
  node:
    container_name: 'bookshelfapi'
    build:
      dockerfile: Dockerfile
      context: './server'
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
        - /app/node_modules
    depends_on:
      - postgresqls
    ports:
      - '3150:3150'
    networks:
      - default
    restart: always
  postgresqls:
    container_name: 'postgresqlpostgis'
    image: 'postgres:10.5'
    ports:
      - '5433:5432'
    volumes:
      - './setup.sql:/docker-entrypoint-initdb.d/setup.sql'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookshelf
    networks:
      - default
    restart: always
networks:
  default:
volumes:
  db_persdata: {}
