version: '3.8'
services:
  frontend:
    container_name: 'frontend'
    build:
      dockerfile: Dockerfile
      context: './frontend'
    environment:
      - NODE_ENV=production
    volumes:
      - /app/node_modules
    depends_on:
      - node
    ports:
      - '4200:4200'
    networks:
      - default
  node:
    container_name: 'bookshelfapi'
    build:
      dockerfile: Dockerfile
      context: './server'
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
        - /app/node_modules
    depends_on:
      - postgresqls
    ports:
      - '3150:3150'
    networks:
      - default
  postgresqls:
    restart: always
    container_name: 'postgresqlpostgis'
    image: 'postgres:10.5'
    ports:
      - '5433:5432'
    volumes:
      - './setup.sql:/docker-entrypoint-initdb.d/setup.sql'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookshelf
    networks:
      - default
networks:
  default:
volumes:
  db_persdata: {}
