CREATE TABLE IF NOT EXISTS `bookshelf` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ISBN` varchar(30) NOT NULL,
  `name` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;